#spring:
#  application:
#    name: UserProvider
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: root
#    url: jdbc:mysql://localhost:3306/db_ljb?serverTimezone=UTC&characterEncoding=UTF8
#    type: com.alibaba.druid.pool.DruidDataSource
server:
  port: 9804
spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 200MB


